-- MySQL Script generated by MySQL Workbench
-- Thu Apr  2 19:56:30 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Delilah-Resto
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Delilah-Resto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Delilah-Resto` DEFAULT CHARACTER SET utf8 ;
USE `Delilah-Resto` ;

-- -----------------------------------------------------
-- Table `Delilah-Resto`.`user_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Delilah-Resto`.`user_type` ;

CREATE TABLE IF NOT EXISTS `Delilah-Resto`.`user_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_type` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Delilah-Resto`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Delilah-Resto`.`user` ;

CREATE TABLE IF NOT EXISTS `Delilah-Resto`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NOT NULL,
  `fullname` VARCHAR(200) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `password` VARCHAR(200) NOT NULL,
  `mail` VARCHAR(200) NOT NULL,
  `phone` VARCHAR(200) NOT NULL,
  `token` VARCHAR(255) NOT NULL,
  `user_type_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_user_type1_idx` (`user_type_id` ASC),
  CONSTRAINT `fk_user_user_type1`
    FOREIGN KEY (`user_type_id`)
    REFERENCES `Delilah-Resto`.`user_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Delilah-Resto`.`state`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Delilah-Resto`.`state` ;

CREATE TABLE IF NOT EXISTS `Delilah-Resto`.`state` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `state` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Delilah-Resto`.`payment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Delilah-Resto`.`payment` ;

CREATE TABLE IF NOT EXISTS `Delilah-Resto`.`payment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `payment_method` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Delilah-Resto`.`order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Delilah-Resto`.`order` ;

CREATE TABLE IF NOT EXISTS `Delilah-Resto`.`order` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `time` TIME NOT NULL,
  `total` FLOAT NOT NULL,
  `state_id` INT NOT NULL,
  `payment_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_order_state1_idx` (`state_id` ASC),
  INDEX `fk_order_payment1_idx` (`payment_id` ASC) ,
  INDEX `fk_order_user1_idx` (`user_id` ASC) ,
  CONSTRAINT `fk_order_state1`
    FOREIGN KEY (`state_id`)
    REFERENCES `Delilah-Resto`.`state` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_payment1`
    FOREIGN KEY (`payment_id`)
    REFERENCES `Delilah-Resto`.`payment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `Delilah-Resto`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Delilah-Resto`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Delilah-Resto`.`product` ;

CREATE TABLE IF NOT EXISTS `Delilah-Resto`.`product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `product_name` VARCHAR(255) NOT NULL,
  `price` FLOAT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Delilah-Resto`.`detail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Delilah-Resto`.`detail` ;

CREATE TABLE IF NOT EXISTS `Delilah-Resto`.`detail` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `order_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `subtotal` FLOAT NOT NULL,
  `quantity` INT NOT NULL,
  PRIMARY KEY (`id`, `order_id`, `product_id`),
  INDEX `fk_product_has_order_order1_idx` (`order_id` ASC) ,
  INDEX `fk_product_has_order_product1_idx` (`product_id` ASC) ,
  CONSTRAINT `fk_product_has_order_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `Delilah-Resto`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_has_order_order1`
    FOREIGN KEY (`order_id`)
    REFERENCES `Delilah-Resto`.`order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Delilah-Resto`.`favorite`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Delilah-Resto`.`favorite` ;

CREATE TABLE IF NOT EXISTS `Delilah-Resto`.`favorite` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  PRIMARY KEY (`id`, `user_id`, `product_id`),
  INDEX `fk_product_has_user_user1_idx` (`user_id` ASC) ,
  INDEX `fk_product_has_user_product1_idx` (`product_id` ASC) ,
  CONSTRAINT `fk_product_has_user_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `Delilah-Resto`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_has_user_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `Delilah-Resto`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
